# Generated by Django 5.1.1 on 2024-09-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinPowder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('weight', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('isolate', 'Isolado'), ('hydrolized', 'Hidrolisado'), ('concentrate', 'Concentrado'), ('clear', 'Clear')], max_length=20)),
                ('image', models.ImageField(upload_to='protein_powders')),
                ('url', models.URLField()),
            ],
        ),
    ]
