# Generated by Django 5.1.1 on 2024-09-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinpowder',
            name='type',
            field=models.CharField(choices=[('isolate', 'Isolado'), ('hydrolyzed', 'Hidrolisado'), ('concentrate', 'Concentrado'), ('clear', 'Clear')], max_length=20),
        ),
    ]
