# Generated by Django 5.1.1 on 2024-09-26 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0003_brand_alter_proteinpowder_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinpowder',
            name='from_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplements.brand'),
            preserve_default=False,
        ),
    ]
