# Generated by Django 5.1.1 on 2024-09-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0005_remove_proteinpowder_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteinpowder',
            old_name='from_brand',
            new_name='brand',
        ),
    ]
