# Generated by Django 5.1.1 on 2024-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0007_creatine'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatine',
            name='form',
            field=models.CharField(choices=[('powder', 'Pó'), ('capsules', 'Cápsulas')], default='powder', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creatine',
            name='type',
            field=models.CharField(choices=[('monohydrate', 'Monohidratada'), ('creapure', 'Creapure®')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proteinpowder',
            name='type',
            field=models.CharField(choices=[('isolate', 'Isolado'), ('concentrate', 'Concentrado'), ('clear', 'Clear'), ('blend', 'Blend')], max_length=20),
        ),
    ]
