# Generated by Django 5.1.1 on 2024-09-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='disallow_votes',
            field=models.BooleanField(default=False),
        ),
    ]
